-- Circla production hardening / feature completion
-- Safe to run after the base schema above.

-- Story owners must be able to see their own expired stories for analytics.
drop policy if exists "stories are viewable" on public.stories;
create policy "stories are viewable" on public.stories
for select using (expires_at > now() or auth.uid() = user_id);

-- Notifications are generated by trusted database triggers.
drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications" on public.notifications
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.create_notification(
  p_user_id uuid,
  p_actor_id uuid,
  p_type text,
  p_entity_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_user_id is null or p_actor_id is null or p_user_id = p_actor_id then
    return;
  end if;
  insert into public.notifications(user_id, actor_id, type, entity_id)
  values (p_user_id, p_actor_id, p_type, p_entity_id);
end;
$$;

create or replace function public.notify_post_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare owner_id uuid;
begin
  select p.user_id into owner_id from public.posts p where p.id = new.post_id;
  perform public.create_notification(owner_id, new.user_id, 'like', new.post_id);
  return new;
end;
$$;

drop trigger if exists post_like_notification on public.post_likes;
create trigger post_like_notification
after insert on public.post_likes
for each row execute function public.notify_post_like();

create or replace function public.notify_post_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare owner_id uuid;
begin
  select p.user_id into owner_id from public.posts p where p.id = new.post_id;
  perform public.create_notification(owner_id, new.user_id, 'comment', new.post_id);
  return new;
end;
$$;

drop trigger if exists post_comment_notification on public.comments;
create trigger post_comment_notification
after insert on public.comments
for each row execute function public.notify_post_comment();

create or replace function public.notify_new_follow()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.create_notification(new.following_id, new.follower_id, 'follow', new.following_id);
  return new;
end;
$$;

drop trigger if exists follow_notification on public.follows;
create trigger follow_notification
after insert on public.follows
for each row execute function public.notify_new_follow();

-- Conversation access helper avoids recursive RLS when a member reads the
-- other member or when the second member is added to a new conversation.
create schema if not exists private;

create or replace function private.is_conversation_member(p_conversation_id uuid)
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1
    from public.conversation_members cm
    where cm.conversation_id = p_conversation_id
      and cm.user_id = (select auth.uid())
  );
$$;

revoke all on function private.is_conversation_member(uuid) from public;
grant execute on function private.is_conversation_member(uuid) to authenticated;

drop policy if exists "members can read conversations" on public.conversations;
create policy "members can read conversations" on public.conversations
for select to authenticated
using ((select private.is_conversation_member(id)));

drop policy if exists "authenticated users create conversations" on public.conversations;
create policy "authenticated users create conversations" on public.conversations
for insert to authenticated
with check ((select auth.uid()) is not null);

drop policy if exists "members can read conversation members" on public.conversation_members;
create policy "members can read conversation members" on public.conversation_members
for select to authenticated
using ((select private.is_conversation_member(conversation_id)));

drop policy if exists "members can add conversation members" on public.conversation_members;
create policy "members can add conversation members" on public.conversation_members
for insert to authenticated
with check (
  (select auth.uid()) = user_id
  or (select private.is_conversation_member(conversation_id))
);

drop policy if exists "members can read messages" on public.messages;
create policy "members can read messages" on public.messages
for select to authenticated
using ((select private.is_conversation_member(conversation_id)));

drop policy if exists "members can send messages" on public.messages;
create policy "members can send messages" on public.messages
for insert to authenticated
with check (
  (select auth.uid()) = sender_id
  and (select private.is_conversation_member(conversation_id))
);

-- Let the existing Postgres Changes subscription receive live chat and
-- notification updates. This is idempotent.
do $$
begin
  begin
    alter publication supabase_realtime add table public.messages;
  exception when duplicate_object then
    null;
  end;
  begin
    alter publication supabase_realtime add table public.notifications;
  exception when duplicate_object then
    null;
  end;
end $$;
