const navItems=document.querySelectorAll("[data-page]");const sections=document.querySelectorAll(".content");function showPage(page){sections.forEach(s=>s.classList.toggle("hidden",s.id!==`page-${page}`));navItems.forEach(n=>n.classList.toggle("active",n.dataset.page===page));window.scrollTo({top:0,behavior:"smooth"})}navItems.forEach(n=>n.addEventListener("click",()=>showPage(n.dataset.page)));document.querySelectorAll(".like").forEach(btn=>btn.addEventListener("click",()=>{btn.classList.toggle("liked-btn");btn.firstChild.textContent=btn.classList.contains("liked-btn")?"♥ ":"♡ ";}));document.getElementById("newPost")?.addEventListener("click",()=>showPage("create"));

const authOverlay=document.getElementById("authOverlay");const authForm=document.getElementById("authForm");const authSwitch=document.getElementById("authSwitch");const authClose=document.getElementById("authClose");const authTitle=document.getElementById("authTitle");const authSubtitle=document.getElementById("authSubtitle");const authSubmit=document.getElementById("authSubmit");const authNameWrap=document.getElementById("authNameWrap");const authMessage=document.getElementById("authMessage");let loginMode=false;

function openAuth(){authOverlay?.classList.add("open");}
function closeAuth(){authOverlay?.classList.remove("open");}
function setAuthMode(login){loginMode=login;authTitle.textContent=login?"Welcome back.":"Join your circle.";authSubtitle.textContent=login?"Log in to continue to Circla.":"Create an account to start sharing moments.";authSubmit.textContent=login?"Log in":"Create account";authNameWrap.classList.toggle("hidden",login);authSwitch.innerHTML=login?'New to Circla? <b>Create an account</b>':'Already have an account? <b>Log in</b>';authMessage.textContent="";}
authSwitch?.addEventListener("click",()=>setAuthMode(!loginMode));authClose?.addEventListener("click",closeAuth);

async function refreshAuth(){if(!window.circlaSupabase)return;const{data:{session}}=await window.circlaSupabase.auth.getSession();const avatar=document.querySelector(".topbar .avatar");if(session){avatar.textContent=(session.user.user_metadata?.display_name||session.user.email||"A").charAt(0).toUpperCase();document.querySelectorAll(".auth-trigger").forEach(x=>x.textContent="Account");}else{document.querySelectorAll(".auth-trigger").forEach(x=>x.textContent="Log in");}}

document.querySelector(".topbar .avatar")?.addEventListener("click",openAuth);
authForm?.addEventListener("submit",async e=>{e.preventDefault();authMessage.textContent="";authSubmit.disabled=true;try{const email=document.getElementById("authEmail").value.trim();const password=document.getElementById("authPassword").value;let result;if(loginMode){result=await window.circlaSupabase.auth.signInWithPassword({email,password});}else{const display_name=document.getElementById("authName").value.trim()||"New Circla User";result=await window.circlaSupabase.auth.signUp({email,password,options:{data:{display_name}}});}if(result.error)throw result.error;authMessage.textContent=loginMode?"You're logged in.":"Account created. Check your email if confirmation is required.";if(loginMode)closeAuth();await refreshAuth();}catch(err){authMessage.textContent=err.message||"Something went wrong.";}finally{authSubmit.disabled=false;}});

document.addEventListener("DOMContentLoaded",()=>{setAuthMode(false);refreshAuth();});